const context = component.contextPath;

export const UrlConstants = {
  // Consent Group
  getConsentGroupByUUID: context + '/api/consent-group/find-by-uuid',
  attachDocuments: context + '/api/files-helper/attach-document',
  consentNamesSearchURL: context + '/consent-group/name-search',
  approveConsentGroupUrl: context + '/api/consent-group/approve',
  updateConsentGroupUrl: context + '/api/consent-group',
  getConsentGroup: context + '/api/consent-group',
  rejectConsentUrl: context + '/api/consent-group/delete',
  createConsentGroupURL: context + '/api/consent-group/create',
  allConsentGroupsUrl: context + '/api/consent-groups',
  sampleSearchUrl: context + '/consent-group/sample-search',
  useRestrictionUrl: context + '/aip/consent-group/use-restriction',
  associatedProjects: context + '/api/consent-group/associatedProjects',
  unlinkAssociatedProjects: context + '/api/consent-group/unlinkAssociatedProjects',
  unlinkAssociatedSampleCollection: context + '/api/consent-group/unlinkAssociatedSampleCollection',
  fillablePdfURL: context + '/api/consent-group/get-fillable-pdf',

  createProjectUrl: context + '/api/project',
  getUserUrl: context + '/api/user/authenticated/user-data',
  projectKeySearchUrl: context + '/search/project-key/autocomplete',
  rejectProjectUrl: context + '/api/project/reject',
  updateProjectUrl: context + '/api/project/update',
  issueReviewUrl: context + '/api/issue-review',
  addExtraPropertiesUrl: context + '/api/project/extra-properties',
  updateExtraPropertiesUrl: context + '/api/project/update-properties',
  clarificationUrl: context + '/api/clarification-request',
  userNameSearchUrl: context + '/search/matching-users',
  sourceDiseasesUrl: context + '/search/matching-diseases-ontologies',
  projectInfoURl: context + '/api/project/get-info',
  searchUrl: context + '/search/general-table-json',

  attachedDocumentsUrl : context + '/api/files-helper/attached-documents',
  rejectDocumentUrl: context + '/api/files-helper/reject-document',
  approveDocumentUrl: context + '/api/files-helper/approve-document',
  removeDocumentUrl: context + '/api/files-helper/delete',
  downloadDocumentUrl: context + '/api/user/authenticated/download-document',
  updateAdminOnlyPropsUrl: context + '/api/project/update-admin-props',
  saveCommentUrl: context + '/api/comments/save',
  getCommentsUrl: context + '/api/comments/list',
  saveExtraPropsUrl: context + '/api/project/extra-properties',
  // sessionUserUrl: context + '/api/user/authenticated',
  emailDulUrl: context + '/api/dul-email-notification',
  projectTypeUrl: context + '/api/project/get-type',
  editUserRoleUrl: context + '/api/edit-user-role',
  getAllUsersUrl: context + '/api/get-users',
  dataUseLetterUrl: context + '/api/data-use-letter',
  dataUseLetterRestrictionUrl: context + '/api/data-use-letter/restriction',
  infoLinkUrl: context + '/api/info-link',

  linkedSampleCollectionsUrl: context + '/api/consent-group/sample-collections',
  sampleConsentLinkUrl: context + '/api/sample-consent-link',
  sampleBreakLinkUrl: context + '/api/break-link',
  sampleApproveLinkUrl: context + '/api/approve-link',
  historyUrl: context + '/api/history',
  submissionsUrl: context + '/api/submissions',
  newRestrictionUrl: context + '/api/data-use/new-restriction',
};

