CREATE TABLE `versioned_issue` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `version` bigint NOT NULL,
  `project_key` varchar(255) NOT NULL,
  `issuenum` bigint DEFAULT NULL,
  `type` varchar(255) NOT NULL,
  `status` varchar(255) NOT NULL,
  `created_at` datetime NOT NULL,
  `created_by` varchar(255) NULL,
  `sequence_number` int NOT NULL DEFAULT '0',
  `summary` text,
  `description` text,
  `reporter` varchar(255) DEFAULT NULL,
  `request_date` datetime NOT NULL,
  `update_date` datetime DEFAULT NULL,
  `expiration_date` datetime DEFAULT NULL,
  `approval_status` varchar(255) DEFAULT NULL,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`));
