hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
    format_sql: true
    show_sql: true
environments:
  test:
    crowd:
      config: /orsp-config/big-query.json
      url: http://localhost:8443/crowd
      username: username
      password: password
      interval: 500
      range: 10
    grails.serverURL: https://localhost:8443
    googleSignInClientId: 237156683917-vacs6fi0b3tqfc10ebqr8n48pdlbtm94.apps.googleusercontent.com
    server:
      contextPath: '/test'
    notifyService:
      sendGridUrl: http://localhost:8443/send
      apiKey: key
      fromAddress: orsp-dev@broadinstitute.org
      defaultRecipient: wloforte@broadinstitute.org
      adminRecipient: wloforte@broadinstitute.org
      securityRecipient: orsp-dev@broadinstitute.org
      agreementsRecipient: orsp-dev@broadinstitute.org
      orspSpecialRecipients: [saltzman@broadinstitute.org, lipscomb@broadinstitute.org, sweisenb@broadinstitute.org, grushton@broadinstitute.org]
      bccRecipients: [grushton@broadinstitute.org]
      replyToRecipient: orsp-dev@broadinstitute.org
      sendGridStatusUrl: http://localhost:8443/
    storage:
      config: /orsp-client.json
      url: http://localhost:9001/
      bucket: broad_institute_orsp_test/
    consent:
      service:
        username: orsp@broadinstitute.org
        password: orspuserpassword
        url: http://localhost:8180/basic/consent
        statusUrl: https://consent.dsde-prod.broadinstitute.org/status
        ontologyUrl: https://consent-ontology.dsde-dev.broadinstitute.org/
        ontologyStatusUrl: https://consent-ontology.dsde-dev.broadinstitute.org/status
    dataBio:
      searchUrl: http://data.bioontology.org/search
      classUrl: http://data.bioontology.org/ontologies
      statusUrl: http://data.bioontology.org/
      apiKey: 4617549f-33f0-4a1f-9a62-c1c8461e7ee6
    bsp:
      sync: false
      service:
        username: orspuser
        password: bspbsp
        allSampleCollectionsUrl: http://bsp/ws/bsp/collection/get_all_collections
        statusUrl: http://bsp/BSP/
    dataSource:
      dbCreate: update
      url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
      pooled: true
      driverClassName: "org.h2.Driver"
      username: "sa"
      password: ""
  development:
    crowd:
      config: /big-query.json
      url: https://crowd.broadinstitute.org:8443/crowd
      username: orsp
      password: hI5#GiU$c1AH
      interval: 500
      range: 10
    grails.serverURL: https://localhost:8443
    gkeServiceName: https://orsp-pub-service
    googleSignInClientId: 237156683917-vacs6fi0b3tqfc10ebqr8n48pdlbtm94.apps.googleusercontent.com
    server:
      contextPath: '/'
    notifyService:
      sendGridUrl: https://api.sendgrid.com/v3/mail/send
      apiKey: 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
      fromAddress: orsp-dev@broadinstitute.org
      defaultRecipient: wloforte@broadinstitute.org
      adminRecipient: wloforte@broadinstitute.org
      securityRecipient: wloforte@broadinstitute.org
      agreementsRecipient: wloforte@broadinstitute.org
      orspSpecialRecipients: [grushton@broadinstitute.org]
      bccRecipients: [grushton@broadinstitute.org]
      replyToRecipient: wloforte@broadinstitute.org
      sendGridStatusUrl: http://status.sendgrid.com/
    storage:
      config: /home/wloforte/Documents/orsp-pub/grails-app/conf/orsp-client.json
      url: https://storage.googleapis.com/
      bucket: orsp_documents_dev_tmp/
    consent:
      service:
        username: orsp@broadinstitute.org
        password: orspuserpassword
        url: http://localhost:8180/basic/consent
        statusUrl: https://consent.dsde-prod.broadinstitute.org/status
        ontologyUrl: https://consent-ontology.dsde-dev.broadinstitute.org/
        ontologyStatusUrl: https://consent-ontology.dsde-dev.broadinstitute.org/status
    dataBio:
      searchUrl: http://data.bioontology.org/search
      classUrl: http://data.bioontology.org/ontologies
      statusUrl: http://data.bioontology.org/
      apiKey: 4617549f-33f0-4a1f-9a62-c1c8461e7ee6
    bsp:
      sync: false
      service:
        username: orspuser
        password: bspbsp
        allSampleCollectionsUrl: http://bsp/ws/bsp/collection/get_all_collections
        statusUrl: http://bsp/BSP/
    dataSource:
      pooled: true
      driverClassName: org.mariadb.jdbc.Driver
      username: root
      password: root
      url: jdbc:mariadb://localhost:3306/bussys_dev
      properties:
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        numTestsPerEvictionRun: 3
        validationQuery: "SELECT 1"
        validationQueryTimeout: 3
        testOnBorrow: true
        testOnReturn: true
        testWhileIdle: true
        defaultTransactionIsolation: 1 #TRANSACTION_READ_UNCOMMITTED
    endpoints:
      metrics:
        enabled: true
  production:
    crowd:
      config: /orsp-config/big-query.json
      url: https://crowd.broadinstitute.org:8443/crowd
      username: orsp
      password: hI5#GiU$c1AH
      interval: 500
      range: 10
    grails.serverURL: https://localhost:8443
    googleSignInClientId: 237156683917-vacs6fi0b3tqfc10ebqr8n48pdlbtm94.apps.googleusercontent.com
    server:
      contextPath: '/'
    notifyService:
      sendGridUrl: https://api.sendgrid.com/v3/mail/send
      apiKey: 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
      fromAddress: orsp-portal@broadinstitute.org
      defaultRecipient: orsp-portal@broadinstitute.org
      adminRecipient: orsp@broadinstitute.org
      securityRecipient: orsp-security@broadinstitute.org
      agreementsRecipient: agreements@broadinstitute.org
      orspSpecialRecipients: [orsp-portal@broadinstitute.org]
      bccRecipients: []
      replyToRecipient: orsp-portal@broadinstitute.org
      sendGridStatusUrl: http://status.sendgrid.com/
    storage:
      config: /orsp-client.json
      url: https://storage.googleapis.com/
      bucket: orsp_documents_production/
    consent:
      service:
        username: orsp@broadinstitute.org
        password: orspuserpassword
        url: https://consent.dsde-prod.broadinstitute.org/basic/consent
        statusUrl: https://consent.dsde-prod.broadinstitute.org/status
        ontologyUrl: https://consent-ontology.dsde-prod.broadinstitute.org/
        ontologyStatusUrl: https://consent-ontology.dsde-prod.broadinstitute.org/status
    dataBio:
      searchUrl: http://data.bioontology.org/search
      classUrl: http://data.bioontology.org/ontologies
      statusUrl: http://data.bioontology.org/
      apiKey: 4617549f-33f0-4a1f-9a62-c1c8461e7ee6
    bsp:
      sync: false
      service:
        username: orspuser
        password: bspbsp
        allSampleCollectionsUrl: http://bsp/ws/bsp/collection/get_all_collections
        statusUrl: http://bsp/BSP/
    dataSource:
      pooled: true
      driverClassName: org.mariadb.jdbc.Driver
      username: bussys_prod
      password: bussys_prod
      url: jdbc:mariadb://34.66.183.65/bussys_prod
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

 ---
grails:
  profile: web
  codegen:
    defaultPackage: orsp
  spring:
    transactionManagement:
      proxies: false
info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
spring:
  groovy:
    template:
      check-template-location: false

 ---
grails:
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: prototype
    upload:
      maxFileSize: 15728640
      maxRequestSize: 15728640
  converters:
    encoding: UTF-8
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlets: html
        taglib: none
        staticparts: none
  plugin.databasemigration:
    changelogLocation: grails-app/migrations
    changelogFileName: changelog-master.xml
    updateOnStart: true
    updateOnStartFileName: changelog-master.xml
endpoints:
  jmx:
    unique-names: true