---
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false

environments:
  test:
    crowd:
      url: http://localhost/crowd
      username: username
      password: password
      interval: 500
      range: 10
    grails.serverURL: http://localhost/test
    googleSignInClientId: testing
    server:
      contextPath: '/test'
    notifyService:
      sendGridUrl: http://localhost/send
      apiKey: key
      fromAddress: orsp-dev@broadinstitute.org
      defaultRecipient: orsp-dev@broadinstitute.org
      orspSpecialRecipients:
        - grushton@broadinstitute.org
      bccRecipients:
        - grushton@broadinstitute.org
      replyToRecipient: orsp-dev@broadinstitute.org
    storage:
      config: /orsp-client.json
      url: http://localhost
      bucket: broad_institute_orsp_test/
    consent:
      service:
        username: un
        password: pw
        url: http://localhost/consent
        ontologyUrl: http://localhost/
    dataBio:
      searchUrl: http://localhost/search
      classUrl: http://localhost/ontologies
      apiKey: test
    bsp:
      sync: false
      service:
        username: un
        password: pw
        allSampleCollectionsUrl: http://localhost/ws/bsp/collection/get_all_collections
    dataSource:
      dbCreate: update
      url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
      pooled: true
      driverClassName: "org.h2.Driver"
      username: "sa"
      password: ""
---
grails:
  profile: web
  codegen:
    defaultPackage: orsp
  spring:
    transactionManagement:
      proxies: false
info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
spring:
  groovy:
    template:
      check-template-location: false

---
grails:
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: prototype
  converters:
    encoding: UTF-8
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlets: html
        taglib: none
        staticparts: none
endpoints:
  jmx:
    unique-names: true
