package org.broadinstitute.orsp.dataUseLetter

enum DataUseLetterFields {
    UID("uid"),
    PROTOCOL_TITLE("protocolTitle"),
    PROTOCOL_NUMBER("protocolNumber"),
    CONSENT_FORM_TITLE("consentFormTitle"),
    PRINCIPAL_INVESTIGATOR("principalInvestigator"),
    DATA_MANAGER_NAME("dataManagerName"),
    DATA_MANAGER_EMAIL("dataManagerEmail"),
    START_DATE("startDate"),
    END_DATE("endDate"),
    ON_GOING_PROCESS("onGoingProcess"),
    REPOSITORY_DEPOSITION("repositoryDeposition"),
    PRIMARY_RESTRICTIONS("primaryRestrictions"),
    NO_RESTRICTIONS("noRestrictions"),
    GENERAL_USE("generalUse"),
    RESEARCH_RESTRICTED("researchRestricted"),
    DISEASE_RESTRICTED("diseaseRestricted"),
    DISEASE_RESTRICTED_OPTIONS("diseaseRestrictedOptions"),
    PARASITIC_DISEASE("parasiticDisease"),
    CANCER("cancer"),
    ENDOCRINE_DISEASE("endocrineDisease"),
    ENDOCRINE_DIABETES("endocrineDiabetes"),
    MENTAL_DISORDER("mentalDisorder"),
    NERVOUS_DISEASE("nervousDisease"),
    EYE_DISEASE("eyeDisease"),
    EAR_DISEASE("earDisease"),
    RESPIRATORY_DISEASE("respiratoryDisease"),
    DIGESTIVE_DISEASE("digestiveDisease"),
    INFLAMMATORY_DISEASE("inflammatoryDisease"),
    SKIN_DISEASE("skinDisease"),
    MUSCULO_SKELETAL_DISEASE("musculoskeletalDisease"),
    GENITOURINARY_DISEASE("genitourinaryDisease"),
    CARDIOVASCULAR_DISEASE("cardiovascularDisease"),
    PREGNANCY("pregnancy"),
    CONGENITAL_MALFORMATION("congenitalMalformation"),
    BLOOD_DISORDER("bloodDisorder"),
    OTHER_DISEASE("otherDisease"),
    OTHER_DISEASE_SPECIFY("otherDiseaseSpecify"),
    COMMERCIAL_PURPOSES("commercialPurposes"),
    METHODS_RESEARCH("methodsResearch"),
    NO_POPULATION_RESTRICTED("noPopulationRestricted"),
    UNDER_18("under18"),
    OVER_18("over18"),
    ONLY_MEN("onlyMen"),
    ONLY_WOMEN("onlyWomen"),
    ETHNIC("ethnic"),
    ETHNIC_SPECIFY("ethnicSpecify"),
    OTHER_RESTRICTIONS("otherRestrictions"),
    DATA_SUBMISSION_PROHIBITION("dataSubmissionProhibition"),
    DATA_USE_CONSENT("dataUseConsent"),
    DATA_DESPOSITION_DESCRIBED("dataDepositionDescribed"),
    REPOSITORY_TYPE("repositoryType"),
    GSR_AVAILABILITY("GSRAvailability"),
    GCR_AVAILABILITY_SPECIFY("GCRAvailabilitySpecify"),
    PRINTED_NAME("printedName"),
    SIGNATURE("signature"),
    POSITION("position"),
    INSTITUTION("institution"),
    SUBMITTED_DATE("date")

    String abbreviation
    private DataUseLetterFields(String abbreviation) {
        this.abbreviation = abbreviation
    }

}
