apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ${HOST_IP}
  labels:
    app: orsp
  name: orsp-ingress
  namespace: ${NAMESPACE}
spec:
  backend:
    serviceName: orsp-service
    servicePort: http
  rules:
  - host: ${HOST_NAME}
    http:
      paths:
      - backend:
          serviceName: orsp-service
          servicePort: http
  tls:
  - hosts:
    - ${HOST_NAME}
    secretName: ${TLS_CERT_SECRET}

