apiVersion: v1
kind: Service
metadata:
  name: ${PROJECT_NAME}-service
  labels:
    app: ${PROJECT_NAME}
  namespace: ${NAMESPACE}
spec:
  selector:
    app: ${PROJECT_NAME}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  sessionAffinity: None
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${PROJECT_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${PROJECT_NAME}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ${PROJECT_NAME}
  template:
    metadata:
      labels:
        app: ${PROJECT_NAME}
    spec:
      containers:
        - name: ${PROJECT_NAME}
          image: gcr.io/${GOOGLE_PROJECT}/${PROJECT_NAME}:${COMMIT}
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_DB_HOST
              value: 127.0.0.1:3306
            # These secrets are required to start the pod.
            # [START cloudsql_secrets]
            - name: MYSQL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /orsp-config
            name: orsp-config
            # [END cloudsql_secrets]
        # [START proxy_container]
        - name: "cloudsql-proxy"
          image: gcr.io/cloudsql-docker/gce-proxy:1.12
          command:
            [
              "/cloud_sql_proxy",
              "-instances=orsp-dev:us-east1:bricc-mysql-dev=tcp:3306",
              "-credential_file=/secrets/cloudsql/credentials.json",
            ]
          # [START cloudsql_security_context]
          securityContext:
            runAsUser: 2 # non-root user
            allowPrivilegeEscalation: false
          # [END cloudsql_security_context]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
          # [END proxy_container]
      # [START volumes]
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: orsp-config
          configMap:
            name: orsp-config-dev
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      # [END volumes]
---

