apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: ${REPO_NAME}
  name: ${REPO_NAME}-service
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ${REPO_NAME}
  sessionAffinity: None
  type: NodePort

