name: Deploy Staging

on:
  push:
    tags:
      - 'staging_*'

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      project_id: orsp-dev
      cluster: orsp-pub-staging
      cluster_region: us-central1-a
      artifact_registry: orsp-repo
      registry_region: us-central1
      deployment: orsp-pub
      image: orsp-staging-img
      project_number: 18883205905
      service_account: circleci-deploy@orsp-dev.iam.gserviceaccount.com
